// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvxthsmtnqnncrafhvsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2eHRoc210bnFubmNyYWZodnNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjkzNzEsImV4cCI6MjA2NDY0NTM3MX0.Hbtt5lT26bHXAk2oAiPXo2kFORiOto5v4vwd6S8AVYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});